Fix ENTER for game restart,
Fixes
```
ERROR: context.random_generator should not be used! Pass generator explicitly.
```
That happened because we were calling context.random_generator from
inside the game_update()'s update()

NOTE:
 - CURRENTLY, Enter restarts the game AND the game recording
   - But can't be used from when we are replaying yet, since we use the
   saved input of ENTER instead
   - I'm not sure if that is the behavior we want, but it is how it
   currently is
    - I'm not sure that game-only restart is that useful though, unless
    we want to try out the early game with different seeds and have that
    part of the same recording
     - Also, that would make it weirder with the frame_count clearly not
     matching the recording, if we had frame_count being reset with the
     rest of the game, as it currently is, but still append to the same
     game_recording buffer. Might make it even more confusing when we
     compare actual game state vs expected game state (our "checksum")

Squashed:
 - Had to reset the `should_game_init` flag in the `if should_game_init`
 code path